# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m25PKMjx7tDu4hLFejVs1RlXZY7TqJ2G
"""

import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Load the Boston Housing dataset
boston = datasets.load_boston()
X = boston.data
y = boston.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Train the regressor
reg = LinearRegression().fit(X_train, y_train)

# Evaluate the regressor on the test data
y_pred = reg.predict(X_test)
mse = np.mean((y_test - y_pred) ** 2)
print("Mean Squared Error:", mse)

# Plot the true vs. predicted values
plt.scatter(y_test, y_pred)
plt.xlabel("True Values")
plt.ylabel("Predicted Values")
plt.show()