# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vW0rSk3B1oNDC1LXpx5FLovHiqCuXojM
"""

import matplotlib.pyplot as plt
import numpy as np
from skimage import data

# Load an image from scikit-image
image = data.coins()

# Convert the image to grayscale
gray_image = np.mean(image, axis=2)

# Display the image using Matplotlib
plt.imshow(gray_image, cmap='gray')
plt.axis('off')
plt.title("Grayscale Image of Coins")
plt.show()