# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vzajcMXJfCC06P-wd0ksmhUkBQEo5XYB
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Generate a sine wave
fs = 100
f = 2
x = np.arange(fs)
y = np.sin(2*np.pi*f * (x/fs))

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)

# Train a linear regression model
reg = LinearRegression().fit(X_train, y_train)

# Use the trained model to make predictions on test data
y_pred = reg.predict(X_test)

# Plot the true and predicted sine waves
plt.plot(X_test, y_test, 'o', label='True Amplitude')
plt.plot(X_test, y_pred, '-', label='Predicted Amplitude')
plt.title("Sine Wave")
plt.xlabel("Sample Index")
plt.ylabel("Amplitude")
plt.legend()
plt.grid(True)
plt.show()